import { Component, Input, computed, inject, signal } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { RouterLink } from '@angular/router';
import { BusinessDataService } from '../../core/services/business-data.service';
@Component({selector:'app-customer-detail',standalone:true,imports:[RouterLink,ReactiveFormsModule],template:`
@if(customer();as c){<a class="back-link" routerLink="/app/customers">← Customers</a><div class="page-head"><div><div class="eyebrow">CUSTOMER / {{c.id}}</div><h1>{{c.name}}</h1><p>{{c.city}} · {{c.contact}}</p></div><div class="head-actions"><button class="secondary" type="button" (click)="openNote()">Add note</button><a class="primary" routerLink="/app/projects" [queryParams]="{new:1,client:c.id}">New project</a></div></div>
<section class="kpi-grid three"><article class="kpi-card"><span>Lifetime value</span><strong>{{money(c.lifetimeValue)}}</strong><small>Commercial history</small></article><article class="kpi-card"><span>Active projects</span><strong>{{c.activeProjects}}</strong><small>Current engagements</small></article><article class="kpi-card"><span>Relationship</span><strong>{{c.status}}</strong><small>Last activity {{c.lastActivity}}</small></article></section>
<section class="detail-grid"><article class="panel"><span class="panel-kicker">CONTACT</span><h2>{{c.contact}}</h2><div class="contact-list"><a [href]="'mailto:'+c.email">{{c.email}}</a><a [href]="'tel:'+c.phone">{{c.phone}}</a><span>{{c.city}}</span></div></article><article class="panel"><span class="panel-kicker">ACTIVE WORK</span><h2>Projects</h2>@for(p of relatedProjects();track p.id){<a class="related-row" [routerLink]="['/app/projects',p.id]"><span><strong>{{p.name}}</strong><small>{{p.status}}</small></span><b>{{p.progress}}%</b></a>}@empty{<div class="empty-state compact-state"><strong>No active projects</strong><span>This customer currently has no open delivery work.</span></div>}</article></section>
<article class="panel customer-notes"><div class="section-title"><div><span class="panel-kicker">CRM NOTES</span><h2>Relationship notes</h2></div></div>@for(note of notes();track note.id){<div class="note-row"><p>{{note.text}}</p><small>{{note.createdAt}}</small></div>}@empty{<div class="empty-state compact-state"><strong>No notes yet</strong><span>Add a short relationship or follow-up note for the team.</span></div>}</article>
@if(showNote()){
<div class="dialog-layer" (click)="closeNote()"><section class="dialog-panel dialog-small" role="dialog" aria-modal="true" aria-labelledby="note-title" (click)="$event.stopPropagation()"><div class="dialog-head"><div><span class="panel-kicker">{{c.name}}</span><h2 id="note-title">Add CRM note</h2></div><button class="icon-close" type="button" (click)="closeNote()" aria-label="Close dialog">×</button></div><form class="product-form" [formGroup]="noteForm" (ngSubmit)="saveNote()"><label class="wide">Note<textarea rows="5" formControlName="text" placeholder="Client preference, follow-up, approval or context..."></textarea>@if(noteForm.controls.text.touched&&noteForm.controls.text.invalid){<small class="error-text">Write at least 3 characters.</small>}</label><div class="dialog-actions wide"><button class="secondary" type="button" (click)="closeNote()">Cancel</button><button class="primary" type="submit">Save note</button></div></form></section></div>}
} @else {<div class="state-panel"><span>404 / CUSTOMER</span><h1>Customer not found.</h1><p>The customer record may have been removed or the URL is incorrect.</p><a class="primary" routerLink="/app/customers">Return to customers</a></div>}`})
export class CustomerDetailComponent{
  private readonly data=inject(BusinessDataService);private readonly fb=inject(FormBuilder);private readonly customerId=signal('');readonly showNote=signal(false);readonly noteForm=this.fb.nonNullable.group({text:['',[Validators.required,Validators.minLength(3)]]});
  @Input() set id(value:string){this.customerId.set(value)}readonly customer=computed(()=>this.data.customerById(this.customerId()));readonly relatedProjects=computed(()=>this.data.projects().filter(p=>p.clientId===this.customerId()&&p.status!=='Completed'));readonly notes=computed(()=>this.data.notesForCustomer(this.customerId()));
  money(value:number){return new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(value)}openNote(){this.noteForm.reset({text:''});this.showNote.set(true)}closeNote(){this.showNote.set(false)}saveNote(){if(this.noteForm.invalid){this.noteForm.markAllAsTouched();return;}this.data.addCustomerNote(this.customerId(),this.noteForm.getRawValue().text);this.closeNote();}
}
